name = "acl"
version = "2.3.2"
description = "Access control list support library and tools"
source = "https://download.savannah.nongnu.org/releases/acl/acl-2.3.2.tar.xz"
sha256 = "97203a72cae99ab89a067fe2210c1cbf052bc492b479eca7d226d9830883b0bd"
source_dir = "acl-2.3.2"
deps = ["attr"]

build_steps = [
  "./configure --prefix=/usr --disable-static",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://download.savannah.nongnu.org/releases/acl/"
version_pattern = "acl-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://download.savannah.nongnu.org/releases/acl/acl-{version}.tar.xz"
source_dir_template = "acl-{version}"
