name = "aml"
version = "1.0.0"
description = "Andri's main loop library"
source = "https://github.com/any1/aml/archive/refs/tags/v1.0.0.tar.gz"
sha256 = "b2b8f743213af39f40e8bc611147d69e2ea9e010b9b19cb65246582338f28d96"
source_dir = "aml-1.0.0"
deps = ["meson", "ninja"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release -Dexamples=false",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://github.com/any1/aml/releases"
version_pattern = "/releases/tag/v?([0-9]+\\.[0-9]+\\.[0-9]+)"
source_template = "https://github.com/any1/aml/archive/refs/tags/v{version}.tar.gz"
source_dir_template = "aml-{version}"
