name = "artanis"
version = "1.3.0"
description = "GNU Artanis web application framework"
source = "https://ftp.gnu.org/gnu/artanis/artanis-1.3.0.tar.gz"
sha256 = "f1532564383fedb7dcd47c43c0b803ec126f66543c7fb6f7c9e64f0fa8979c99"
source_dir = "artanis-1.3.0"
deps = ["guile"]
build_steps = ["./configure", "make", "make DESTDIR=${MAHOU_DESTDIR} install"]

[update]
check_url = "https://ftp.gnu.org/gnu/artanis/"
version_pattern = "artanis-([0-9][^\"/]+)\\.tar\\.gz"
source_template = "https://ftp.gnu.org/gnu/artanis/artanis-{version}.tar.gz"
source_dir_template = "artanis-{version}"
