name = "aspell-dict-or"
version = "0.03-1"
description = "Aspell Odia dictionary"
source = "https://ftp.gnu.org/gnu/aspell/dict/or/aspell6-or-0.03-1.tar.bz2"
sha256 = "d6ffa369f8918d74cdea966112bc5cb700e09dca5ac6b968660cfc22044ef24f"
source_dir = "aspell6-or-0.03-1"
deps = ["aspell"]
build_steps = ["./configure", "make", "make DESTDIR=${MAHOU_DESTDIR} install"]

[update]
check_url = "https://ftp.gnu.org/gnu/aspell/dict/or/"
version_pattern = "aspell6-or-([^\"/]+)\\.tar\\.bz2"
source_template = "https://ftp.gnu.org/gnu/aspell/dict/or/aspell6-or-{version}.tar.bz2"
source_dir_template = "aspell6-or-{version}"
