name = "bat"
version = "0.26.1"
description = "cat(1) clone with syntax highlighting and Git integration"
source = "https://github.com/sharkdp/bat/archive/v0.26.1.tar.gz"
sha256 = "4474de87e084953eefc1120cf905a79f72bbbf85091e30cf37c9214eafcaa9c9"
source_dir = "bat-0.26.1"
deps = []

build_steps = [
  "cargo install --path . --locked --root ${MAHOU_DESTDIR}/usr",
  "rm -f ${MAHOU_DESTDIR}/usr/.crates.toml ${MAHOU_DESTDIR}/usr/.crates2.json",
]

[update]
check_url = "https://github.com/sharkdp/bat/releases"
version_pattern = "/releases/tag/v?([0-9][^\"/-]*)"
source_template = "https://github.com/sharkdp/bat/archive/v{version}.tar.gz"
source_dir_template = "bat-{version}"
