name = "bzip2"
version = "1.0.8"
description = "A high-quality data compressor used extensively by Gentoo Linux"
source = "https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"
sha256 = "ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269"
source_dir = "bzip2-1.0.8"
deps = []

build_steps = [
  "make",
  "make PREFIX=/usr DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://sourceware.org/pub/bzip2/"
version_pattern = "bzip2-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://sourceware.org/pub/bzip2/bzip2-{version}.tar.gz"
source_dir_template = "bzip2-{version}"
