name = "cmake"
version = "4.3.3"
description = "Cross-platform build system generator"
source = "https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3.tar.gz"
sha256 = "cba4bb7a44edf2877bb6f059932896383babe435b3a8c3b5df48b4aa41c9bb85"
source_dir = "cmake-4.3.3"
deps = ["bzip2", "curl", "expat", "libarchive", "ncurses", "openssl", "xz", "zlib", "zstd"]

build_steps = [
  "./bootstrap --prefix=/usr --system-curl --system-expat --system-zlib --system-bzip2 --system-liblzma --system-zstd --parallel=$(nproc)",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://github.com/Kitware/CMake/releases"
version_pattern = "/releases/tag/v?([0-9]+\\.[0-9]+\\.[0-9]+)"
source_template = "https://github.com/Kitware/CMake/releases/download/v{version}/cmake-{version}.tar.gz"
source_dir_template = "cmake-{version}"
