name = "dmenu"
version = "5.4"
description = "a generic, highly customizable, and efficient menu for the X Window System"
source = "https://dl.suckless.org/tools/dmenu-5.4.tar.gz"
sha256 = "8fbace2a0847aa80fe861066b118252dcc7b4ca0a0a8f3a93af02da8fb6cd453"
source_dir = "dmenu-5.4"
deps = ["libX11", "libXft"]

build_steps = [
  "make",
  "make PREFIX=/usr DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://dl.suckless.org/tools/"
version_pattern = "dmenu-([0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://dl.suckless.org/tools/dmenu-{version}.tar.gz"
source_dir_template = "dmenu-{version}"
