name = "ed"
version = "1.4"
description = "GNU line-oriented text editor"
source = "https://ftp.gnu.org/gnu/ed/ed-1.4.tar.gz"
sha256 = "db36da85ee1a9d8bafb4b041bd4c8c11becba0c43ec446353b67045de1634fda"
source_dir = "ed-1.4"
deps = []
build_steps = ["./configure", "make", "make DESTDIR=${MAHOU_DESTDIR} install"]

[update]
check_url = "https://ftp.gnu.org/gnu/ed/"
version_pattern = "ed-([^\"/]+)\\.tar\\.gz"
source_template = "https://ftp.gnu.org/gnu/ed/ed-{version}.tar.gz"
source_dir_template = "ed-{version}"
