name = "encodings"
version = "1.1.0"
description = "X.Org font encoding files"
source = "https://www.x.org/releases/individual/font/encodings-1.1.0.tar.xz"
sha256 = "9ff13c621756cfa12e95f32ba48a5b23839e8f577d0048beda66c67dab4de975"
source_dir = "encodings-1.1.0"
deps = ["mkfontscale", "pkgconf"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://www.x.org/releases/individual/font/"
version_pattern = "encodings-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://www.x.org/releases/individual/font/encodings-{version}.tar.xz"
source_dir_template = "encodings-{version}"
