name = "fd"
version = "10.4.2"
description = "Alternative to find that provides sensible defaults for 80% of the use cases"
source = "https://github.com/sharkdp/fd/archive/v10.4.2.tar.gz"
sha256 = "3a7e027af8c8e91c196ac259c703d78cd55c364706ddafbc66d02c326e57a456"
source_dir = "fd-10.4.2"
deps = []

build_steps = [
  "cargo install --path . --locked --root ${MAHOU_DESTDIR}/usr",
  "rm -f ${MAHOU_DESTDIR}/usr/.crates.toml ${MAHOU_DESTDIR}/usr/.crates2.json",
]

[update]
check_url = "https://github.com/sharkdp/fd/releases"
version_pattern = "/releases/tag/([^\"/]+)"
source_template = "https://github.com/sharkdp/fd/archive/v{version}.tar.gz"
source_dir_template = "fd-{version}"
