name = "fontopia"
version = "2.0"
description = "Console font editor"
source = "https://ftp.gnu.org/gnu/fontopia/fontopia-2.0.tar.gz"
sha256 = "0daa54bb1153f6108661e619f9b5e717f6c1e2385b25fc3a5135d4f64e5b6773"
source_dir = "fontopia-2.0"
deps = ["ncurses"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://ftp.gnu.org/gnu/fontopia/"
version_pattern = "fontopia-([0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://ftp.gnu.org/gnu/fontopia/fontopia-{version}.tar.gz"
source_dir_template = "fontopia-{version}"
