name = "font-util"
version = "1.4.2"
description = "X.Org font utilities and font metadata"
source = "https://www.x.org/releases/individual/font/font-util-1.4.2.tar.xz"
sha256 = "02e4f8afdcf03cc8372ca9c37aa104b1e36b47722dbc79531be08f0a4c622999"
source_dir = "font-util-1.4.2"
deps = ["pkgconf", "util-macros"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://www.x.org/releases/individual/font/"
version_pattern = "font-util-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://www.x.org/releases/individual/font/font-util-{version}.tar.xz"
source_dir_template = "font-util-{version}"
