name = "gegl"
version = "0.4.70"
description = "Graph-based image processing framework"
source = "https://download.gimp.org/pub/gegl/0.4/gegl-0.4.70.tar.xz"
sha256 = "47f50d9c3aecd375deb48c11ebfead52d162e4fc162a4b3d44618277f1faec02"
source_dir = "gegl-0.4.70"
deps = ["babl", "glib", "json-glib", "libjpeg-turbo", "libpng", "meson", "ninja"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release -Ddocs=false -Dgtk-doc=false -Dgi-docgen=disabled -Dintrospection=false -Dvapigen=disabled -Dgdk-pixbuf=disabled -Dgexiv2=disabled -Dgraphviz=disabled -Djasper=disabled -Dlcms=disabled -Dlensfun=disabled -Dlibav=disabled -Dlibraw=disabled -Dlibrsvg=disabled -Dlibspiro=disabled -Dlibtiff=disabled -Dlibv4l=disabled -Dlibv4l2=disabled -Dlua=disabled -Dmrg=disabled -Dopenexr=disabled -Dopenmp=disabled -Dcairo=disabled -Dpango=disabled -Dpangocairo=disabled -Dpoppler=disabled -Dpygobject=disabled -Dsdl2=disabled -Dumfpack=disabled -Dwebp=disabled",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://download.gimp.org/pub/gegl/0.4/"
version_pattern = "gegl-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://download.gimp.org/pub/gegl/0.4/gegl-{version}.tar.xz"
source_dir_template = "gegl-{version}"
