name = "gmp"
version = "6.3.0"
description = "Library for arbitrary precision arithmetic"
source = "https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz"
sha256 = "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"
source_dir = "gmp-6.3.0"
deps = []

build_steps = [
  "./configure --prefix=/usr --enable-cxx",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://gmplib.org/download/gmp/"
version_pattern = "gmp-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://gmplib.org/download/gmp/gmp-{version}.tar.xz"
source_dir_template = "gmp-{version}"
