name = "gnome-maps"
version = "50.1"
description = "GNOME maps application"
source = "https://download.gnome.org/sources/gnome-maps/50/gnome-maps-50.1.tar.xz"
sha256 = "42cdf0367f945ce3db1203a6bcfd1d5f5f36d9cac361c81c18567b93130de9eb"
source_dir = "gnome-maps-50.1"
deps = ["glib", "gtk4", "libadwaita", "libshumate"]
build_steps = ["meson setup build --prefix=/usr --buildtype=release", "ninja -C build", "DESTDIR=${MAHOU_DESTDIR} ninja -C build install"]

[update]
check_url = "https://download.gnome.org/sources/gnome-maps/50/"
version_pattern = "gnome-maps-([^\"/]+)\\.tar\\.xz"
source_template = "https://download.gnome.org/sources/gnome-maps/50/gnome-maps-{version}.tar.xz"
source_dir_template = "gnome-maps-{version}"
