name = "gsl"
version = "2.8"
description = "GNU Scientific Library"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/gsl/"

source = "https://ftp.gnu.org/gnu/gsl/gsl-2.8.tar.gz"
sha256 = "6a99eeed15632c6354895b1dd542ed5a855c0f15d9ad1326c6fe2b2c9e423190"
source_dir = "gsl-2.8"

deps = []

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://ftp.gnu.org/gnu/gsl/"
version_pattern = "gsl-([0-9]+\\.[0-9]+(?:\\.[0-9]+)?)\\.tar\\.gz"
source_template = "https://ftp.gnu.org/gnu/gsl/gsl-{version}.tar.gz"
source_dir_template = "gsl-{version}"
