name = "gtkmm"
version = "3.24.10"
description = "C++ interface for GTK+"
source = "https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.10.tar.xz"
sha256 = "7ab7e2266808716e26c39924ace1fb46da86c17ef39d989624c42314b32b5a76"
source_dir = "gtkmm-3.24.10"
deps = ["atkmm", "cairomm", "glibmm", "gtk+", "mm-common", "pangomm"]

build_steps = [
  "meson setup build --prefix=/usr --libdir=lib --buildtype=release --wrap-mode=nofallback -Dmaintainer-mode=false -Dbuild-documentation=false {feature_flags}",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[features.demos]
enabled = false
build_flags = ["-Dbuild-demos=true"]
disabled_build_flags = ["-Dbuild-demos=false"]

[features.tests]
enabled = false
build_flags = ["-Dbuild-tests=true"]
disabled_build_flags = ["-Dbuild-tests=false"]

[update]
check_url = "https://download.gnome.org/sources/gtkmm/3.24/"
version_pattern = "gtkmm-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://download.gnome.org/sources/gtkmm/3.24/gtkmm-{version}.tar.xz"
source_dir_template = "gtkmm-{version}"
