name = "iniparser"
version = "4.2.6"
description = "Free stand-alone ini file parsing library"
source = "https://gitlab.com/iniparser/iniparser/-/archive/v4.2.6/iniparser-v4.2.6.tar.bz2"
sha256 = "30f8eaf74b8c4667f2adef4c6b5c50699d1fa6e3ad65b65b0993d414d7ee3118"
source_dir = "iniparser-v4.2.6"
deps = []

build_steps = [
  "cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release",
  "cmake --build build",
  "DESTDIR=${MAHOU_DESTDIR} cmake --install build",
]

[update]
check_url = "https://gitlab.com/iniparser/iniparser/-/tags"
version_pattern = "iniparser-v([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.bz2"
source_template = "https://gitlab.com/iniparser/iniparser/-/archive/v{version}/iniparser-v{version}.tar.bz2"
source_dir_template = "iniparser-v{version}"
