name = "lcms"
version = "2.19.1"
description = "A lightweight, speed optimized color management engine"
source = "https://github.com/mm2/Little-CMS/releases/download/lcms2.19.1/lcms2-2.19.1.tar.gz"
sha256 = "bfc54f7bab59fbc921012014a8032e4cba4abd46db47d46b76416a8c0b2815c8"
source_dir = "lcms2-2.19.1"
deps = []

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://github.com/mm2/Little-CMS/releases"
version_pattern = "/releases/tag/([^\"/]+)"
source_template = "https://github.com/mm2/Little-CMS/releases/download/lcms{version}/lcms2-{version}.tar.gz"
source_dir_template = "lcms2-{version}"
