name = "lib32-libXext"
version = "1.3.7"
description = "X11 miscellaneous extensions library (32-bit)"
source = "https://www.x.org/releases/individual/lib/libXext-1.3.7.tar.xz"
sha256 = "6c643c7035cdacf67afd68f25d01b90ef889d546c9fcd7c0adf7c2cf91e3a32d"
source_dir = "libXext-1.3.7"
deps = ["lib32-libX11", "xorg-proto"]

build_steps = [
  "make distclean || true",
  "CFLAGS='-m32 -O2' LDFLAGS='-m32' PKG_CONFIG_LIBDIR=/usr/lib32/pkgconfig:/usr/share/pkgconfig ./configure --prefix=/usr --libdir=/usr/lib32 --host=i686-pc-linux-gnu",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://www.x.org/releases/individual/lib/"
version_pattern = "libXext-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://www.x.org/releases/individual/lib/libXext-{version}.tar.xz"
source_dir_template = "libXext-{version}"
