name = "libaio"
version = "0.3.113"
description = "Linux kernel asynchronous I/O access library"
source = "https://releases.pagure.org/libaio/libaio-0.3.113.tar.gz"
sha256 = "2c44d1c5fd0d43752287c9ae1eb9c023f04ef848ea8d4aafa46e9aedb678200b"
source_dir = "libaio-0.3.113"
deps = []

build_steps = [
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} prefix=/usr libdir=/usr/lib install",
]

[update]
check_url = "https://releases.pagure.org/libaio/"
version_pattern = "libaio-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://releases.pagure.org/libaio/libaio-{version}.tar.gz"
source_dir_template = "libaio-{version}"
