name = "libdisplay-info"
version = "0.3.0"
description = "EDID and DisplayID library"
source = "https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases/0.3.0/downloads/libdisplay-info-0.3.0.tar.xz"
sha256 = "6ae77cd937f9cf7d1321d35c116062c4911e8447010a6a713ac4286f7a9d5987"
source_dir = "libdisplay-info-0.3.0"
deps = ["hwdata", "meson", "ninja"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases"
version_pattern = "/-/releases/([0-9]+\\.[0-9]+\\.[0-9]+)"
source_template = "https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases/{version}/downloads/libdisplay-info-{version}.tar.xz"
source_dir_template = "libdisplay-info-{version}"
