name = "libepoxy"
version = "1.5.10"
description = "Library for handling OpenGL function pointer management"
source = "https://github.com/anholt/libepoxy/archive/1.5.10.tar.gz"
sha256 = "a7ced37f4102b745ac86d6a70a9da399cc139ff168ba6b8002b4d8d43c900c15"
source_dir = "libepoxy-1.5.10"
deps = []

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://github.com/anholt/libepoxy/releases"
version_pattern = "/releases/tag/([^\"/]+)"
source_template = "https://github.com/anholt/libepoxy/archive/{version}.tar.gz"
source_dir_template = "libepoxy-{version}"
