name = "libhandy"
version = "1.8.3"
description = "GTK widgets for mobile-friendly applications"
source = "https://download.gnome.org/sources/libhandy/1.8/libhandy-1.8.3.tar.xz"
sha256 = "05b497229073ff557f10b326e074c5066f8743a302d4820ab97bcb5cd2dab087"
source_dir = "libhandy-1.8.3"
deps = ["glib"]
build_steps = ["meson setup build --prefix=/usr --buildtype=release", "ninja -C build", "DESTDIR=${MAHOU_DESTDIR} ninja -C build install"]

[update]
check_url = "https://download.gnome.org/sources/libhandy/1.8/"
version_pattern = "libhandy-([^\"/]+)\\.tar\\.xz"
source_template = "https://download.gnome.org/sources/libhandy/1.8/libhandy-{version}.tar.xz"
source_dir_template = "libhandy-{version}"
