name = "libunistring"
version = "1.4.2"
description = "Library for manipulating Unicode and C strings according to Unicode standard"
source = "https://ftpmirror.gnu.org/libunistring/libunistring-1.4.2.tar.xz"
sha256 = "5b46e74377ed7409c5b75e7a96f95377b095623b689d8522620927964a41499c"
source_dir = "libunistring-1.4.2"
deps = []

build_steps = [
  "./configure --prefix=/usr --disable-static",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
  "rm -f ${MAHOU_DESTDIR}/usr/lib/libunistring.la ${MAHOU_DESTDIR}/usr/lib64/libunistring.la",
]

[update]
check_url = "https://ftp.gnu.org/gnu/libunistring/"
version_pattern = "libunistring-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://ftpmirror.gnu.org/libunistring/libunistring-{version}.tar.xz"
source_dir_template = "libunistring-{version}"
