name = "libvorbis"
version = "1.3.7"
description = "The Ogg Vorbis sound file format library"
source = "https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz"
sha256 = "b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b"
source_dir = "libvorbis-1.3.7"
deps = ["libogg"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://downloads.xiph.org/releases/vorbis/"
version_pattern = "libvorbis-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://downloads.xiph.org/releases/vorbis/libvorbis-{version}.tar.xz"
source_dir_template = "libvorbis-{version}"
