name = "libwacom"
version = "2.19.0"
description = "Library for identifying Wacom tablets and their model-specific features"
source = "https://github.com/linuxwacom/libwacom/releases/download/libwacom-2.19.0/libwacom-2.19.0.tar.xz"
sha256 = "8dd84e75d322aa5f33b2fe781cb67efa5706fedcf483737b4657557f33055a93"
source_dir = "libwacom-2.19.0"
deps = ["glib", "libevdev", "libgudev"]

build_steps = [
  "meson setup build --prefix=/usr --libdir=lib --buildtype=release -Ddocumentation=disabled -Dtests=disabled",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://github.com/linuxwacom/libwacom/releases"
version_pattern = "/releases/tag/libwacom-([0-9]+\\.[0-9]+\\.[0-9]+)"
source_template = "https://github.com/linuxwacom/libwacom/releases/download/libwacom-{version}/libwacom-{version}.tar.xz"
source_dir_template = "libwacom-{version}"
