name = "lsh"
version = "2.1"
description = "GNU SSH2 protocol implementation"
source = "https://ftp.gnu.org/gnu/lsh/lsh-2.1.tar.gz"
sha256 = "8bbf94b1aa77a02cac1a10350aac599b7aedda61881db16606debeef7ef212e3"
source_dir = "lsh-2.1"
deps = ["gmp", "nettle", "zlib"]
build_steps = ["./configure --prefix=/usr", "make", "make DESTDIR=${MAHOU_DESTDIR} install"]
[update]
check_url = "https://ftp.gnu.org/gnu/lsh/"
version_pattern = "lsh-([0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://ftp.gnu.org/gnu/lsh/lsh-{version}.tar.gz"
source_dir_template = "lsh-{version}"
