name = "lzop"
version = "1.04"
description = "Utility for fast (even real-time) compression/decompression"
source = "https://www.lzop.org/download/lzop-1.04.tar.gz"
sha256 = "7e72b62a8a60aff5200a047eea0773a8fb205caf7acbe1774d95147f305a2f41"
source_dir = "lzop-1.04"
deps = []

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://www.lzop.org/download/"
version_pattern = "lzop-([0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://www.lzop.org/download/lzop-{version}.tar.gz"
source_dir_template = "lzop-{version}"
