name = "m4"
version = "1.4.20"
description = "GNU macro processor"
source = "https://ftpmirror.gnu.org/m4/m4-1.4.20.tar.xz"
sha256 = "e236ea3a1ccf5f6c270b1c4bb60726f371fa49459a8eaaebc90b216b328daf2b"
source_dir = "m4-1.4.20"
deps = []

build_steps = [
  "./configure --prefix=/usr",
  "sed -i 's/__GNUC__ >= 15/__GNUC__ >= 99/g' lib/stdlib.in.h lib/string.in.h lib/wchar.in.h lib/config.h",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://ftp.gnu.org/gnu/m4/"
version_pattern = "m4-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://ftpmirror.gnu.org/m4/m4-{version}.tar.xz"
source_dir_template = "m4-{version}"
