name = "mtools"
version = "4.0.49"
description = "Utilities for accessing MS-DOS disks"
source = "https://ftp.gnu.org/gnu/mtools/mtools-4.0.49.tar.bz2"
sha256 = "6fe5193583d6e7c59da75e63d7234f76c0b07caf33b103894f46f66a871ffc9f"
source_dir = "mtools-4.0.49"
deps = []

build_steps = [
  "./configure --prefix=/usr --without-x --disable-floppyd",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://ftp.gnu.org/gnu/mtools/"
version_pattern = "mtools-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.bz2"
source_template = "https://ftp.gnu.org/gnu/mtools/mtools-{version}.tar.bz2"
source_dir_template = "mtools-{version}"
