name = "neatvnc"
version = "1.0.0"
description = "Liberally licensed VNC server library"
source = "https://github.com/any1/neatvnc/archive/refs/tags/v1.0.0.tar.gz"
sha256 = "993dedc30e72981650770c04438e9759537e4677010e2dab5e792c39afe74601"
source_dir = "neatvnc-1.0.0"
deps = ["aml", "meson", "ninja", "pixman", "zlib"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release -Dbenchmarks=false -Dexamples=false -Dtests=false {feature_flags}",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[features.h264]
enabled = false
deps = ["ffmpeg", "libdrm", "mesa"]
build_flags = ["-Dh264=enabled", "-Dgbm=enabled"]
disabled_build_flags = ["-Dh264=disabled", "-Dgbm=disabled"]

[features.jpeg]
deps = ["libjpeg-turbo"]
build_flags = ["-Djpeg=enabled"]
disabled_build_flags = ["-Djpeg=disabled"]

[features.nettle]
deps = ["nettle"]
build_flags = ["-Dnettle=enabled"]
disabled_build_flags = ["-Dnettle=disabled"]

[features.tls]
deps = ["gnutls"]
build_flags = ["-Dtls=enabled"]
disabled_build_flags = ["-Dtls=disabled"]

[update]
check_url = "https://github.com/any1/neatvnc/releases"
version_pattern = "/releases/tag/v?([0-9]+\\.[0-9]+\\.[0-9]+)"
source_template = "https://github.com/any1/neatvnc/archive/refs/tags/v{version}.tar.gz"
source_dir_template = "neatvnc-{version}"
