name = "pango"
version = "1.57.1"
description = "Internationalized text layout and rendering library"
source = "https://download.gnome.org/sources/pango/1.57/pango-1.57.1.tar.xz"
sha256 = "e65d6d117080dc3aeeb7d8b4b3b518f7383aa2e6cfce23117c623cd624764c2f"
source_dir = "pango-1.57.1"
deps = ["cairo", "fontconfig", "freetype", "glib", "harfbuzz"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release --wrap-mode=nofallback -Dfontconfig=enabled -Dfreetype=enabled -Dcairo=enabled -Ddocumentation=false -Dgtk_doc=false -Dman-pages=false -Dbuild-testsuite=false -Dbuild-examples=false -Dlibthai=disabled {feature_flags}",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[features.introspection]
deps = ["gobject-introspection"]
build_flags = ["-Dintrospection=enabled"]
disabled_build_flags = ["-Dintrospection=disabled"]

[features.xft]
deps = ["libXft"]
build_flags = ["-Dxft=enabled"]
disabled_build_flags = ["-Dxft=disabled"]

[update]
check_url = "https://download.gnome.org/sources/pango/1.57/"
version_pattern = "pango-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://download.gnome.org/sources/pango/1.57/pango-{version}.tar.xz"
source_dir_template = "pango-{version}"
