name = "patchutils"
version = "0.4.5"
description = "Utilities for manipulating patch files"
source = "https://github.com/twaugh/patchutils/releases/download/0.4.5/patchutils-0.4.5.tar.xz"
sha256 = "8386a35a4d2d3cbc28fdcc93c5be007c382c78e3ee079070139f0d822e013325"
source_dir = "patchutils-0.4.5"
deps = ["diffutils", "patch"]

build_steps = [
  "./configure --prefix=/usr --with-diff=/usr/bin/diff --with-patch=/usr/bin/patch {feature_flags}",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[features.pcre2]
deps = ["pcre2"]
build_flags = ["--with-pcre2=/usr"]
disabled_build_flags = ["--with-pcre2=no"]

[update]
check_url = "https://github.com/twaugh/patchutils/releases"
version_pattern = "/releases/tag/([0-9]+\\.[0-9]+\\.[0-9]+)"
source_template = "https://github.com/twaugh/patchutils/releases/download/{version}/patchutils-{version}.tar.xz"
source_dir_template = "patchutils-{version}"
