name = "pavucontrol"
version = "6.1"
description = "Pulseaudio Volume Control, GTK based mixer for Pulseaudio"
source = "https://freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-6.1.tar.xz"
sha256 = "0dce61c1088eafa04c270e1fb79eb7aff47e98567f7d28c65a7bee6cd24e415d"
source_dir = "pavucontrol-6.1"
deps = ["gtkmm", "pulseaudio"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://freedesktop.org/software/pulseaudio/pavucontrol/"
version_pattern = "pavucontrol-([0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-{version}.tar.xz"
source_dir_template = "pavucontrol-{version}"
