name = "pbzip2"
version = "1.1.13"
description = "Parallel bzip2 file compressor"
source = "https://launchpad.net/pbzip2/1.1/1.1.13/+download/pbzip2-1.1.13.tar.gz"
sha256 = "8fd13eaaa266f7ee91f85c1ea97c86d9c9cc985969db9059cdebcb1e1b7bdbe6"
source_dir = "pbzip2-1.1.13"
deps = ["bzip2"]

build_steps = [
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} PREFIX=/usr install",
]

[update]
check_url = "https://launchpad.net/pbzip2/1.1"
version_pattern = "pbzip2-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://launchpad.net/pbzip2/1.1/{version}/+download/pbzip2-{version}.tar.gz"
source_dir_template = "pbzip2-{version}"
