name = "slurp"
version = "1.5.0"
description = "Select a region in a Wayland compositor and print it to the standard output"
source = "https://github.com/emersion/slurp/releases/download/v1.5.0/slurp-1.5.0.tar.gz"
sha256 = "eeb282b2adc8db5614b852596340b69da6f3954cf6cfbdc4392da509c934208a"
source_dir = "slurp-1.5.0"
deps = ["cairo", "libxkbcommon", "wayland", "wayland-protocols"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release -Dman-pages=disabled",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://github.com/emersion/slurp/releases"
version_pattern = "/releases/tag/v?([0-9]+\\.[0-9]+\\.[0-9]+)"
source_template = "https://github.com/emersion/slurp/releases/download/v{version}/slurp-{version}.tar.gz"
source_dir_template = "slurp-{version}"
