name = "tmux"
version = "3.6a"
description = "Terminal multiplexer"
source = "https://github.com/tmux/tmux/releases/download/3.6a/tmux-3.6a.tar.gz"
sha256 = "b6d8d9c76585db8ef5fa00d4931902fa4b8cbe8166f528f44fc403961a3f3759"
source_dir = "tmux-3.6a"
deps = ["libevent", "ncurses"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://github.com/tmux/tmux/releases"
version_pattern = "/releases/tag/([^\"/]+)"
source_template = "https://github.com/tmux/tmux/releases/download/{version}/tmux-{version}.tar.gz"
source_dir_template = "tmux-{version}"
