name = "unbound"
version = "1.25.0"
description = "Validating, recursive, caching DNS resolver"
source = "https://nlnetlabs.nl/downloads/unbound/unbound-1.25.0.tar.gz"
sha256 = "062a6eda723fe2f041bee4079b76981569f1d12e066bbd74800242fc1ebddec7"
source_dir = "unbound-1.25.0"
deps = ["expat", "libevent", "openssl"]

build_steps = [
  "./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-libevent=/usr --with-libexpat=/usr --without-pyunbound --without-pythonmodule --disable-subnet {feature_flags}",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[features.cachedb]
deps = ["hiredis"]
build_flags = ["--with-libhiredis=/usr"]
disabled_build_flags = ["--without-libhiredis"]

[features.http2]
deps = ["nghttp2"]
build_flags = ["--with-libnghttp2=/usr"]
disabled_build_flags = ["--without-libnghttp2"]

[update]
check_url = "https://nlnetlabs.nl/downloads/unbound/"
version_pattern = "unbound-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://nlnetlabs.nl/downloads/unbound/unbound-{version}.tar.gz"
source_dir_template = "unbound-{version}"
