name = "unordered_dense"
version = "4.8.1"
description = "Fast densely stored hash map and hash set for C++"
source = "https://github.com/martinus/unordered_dense/archive/refs/tags/v4.8.1.tar.gz"
sha256 = "9f7202ec6d8353932ef865d33f5872e4b7a1356e9032da7cd09c3a0c5bb2b7de"
source_dir = "unordered_dense-4.8.1"
deps = ["cmake"]
build_steps = [
    "cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DANKERL_ENABLE_MODULES=OFF -DANKERL_ENABLE_EXAMPLE=OFF",
    "cmake --build build",
    "DESTDIR=${MAHOU_DESTDIR} cmake --install build",
]

[update]
check_url = "https://github.com/martinus/unordered_dense/releases"
version_pattern = "/releases/tag/v?([0-9][^\"/-]*)"
source_template = "https://github.com/martinus/unordered_dense/archive/refs/tags/v{version}.tar.gz"
source_dir_template = "unordered_dense-{version}"
