name = "wayland-protocols"
version = "1.48"
description = "Wayland protocol files"
source = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/1.48/downloads/wayland-protocols-1.48.tar.xz"
sha256 = "398036ac0eb6484982ddbde7ff86848d753231f9cdeeae983f06b52946625aa1"
source_dir = "wayland-protocols-1.48"
deps = []

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/tags"
version_pattern = "/-/tags/([0-9]+\\.[0-9]+)"
source_template = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/{version}/downloads/wayland-protocols-{version}.tar.xz"
source_dir_template = "wayland-protocols-{version}"
