name = "xapian"
version = "2.0.0"
description = "Xapian Probabilistic Information Retrieval library"
source = "https://oligarchy.co.uk/xapian/2.0.0/xapian-core-2.0.0.tar.xz"
sha256 = "6cea3f49952a47224439a40bdb3608f928d121ad8721b9921cc42802d548ecf8"
source_dir = "xapian-core-2.0.0"
deps = ["zlib"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://oligarchy.co.uk/xapian/"
version_pattern = "xapian-core-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://oligarchy.co.uk/xapian/{version}/xapian-core-{version}.tar.xz"
source_dir_template = "xapian-core-{version}"
