name = "xcb-proto"
version = "1.17.0"
description = "XCB protocol descriptions"
source = "https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.17.0.tar.xz"
sha256 = "2c1bacd2110f4799f74de6ebb714b94cf6f80fb112316b1219480fd22562148c"
source_dir = "xcb-proto-1.17.0"
deps = ["xorg-proto"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://xorg.freedesktop.org/archive/individual/proto/"
version_pattern = "xcb-proto-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-{version}.tar.xz"
source_dir_template = "xcb-proto-{version}"
