name = "xf86-video-r128"
version = "6.13.0"
description = "X.Org ATI Rage 128 video driver"
source = "https://www.x.org/releases/individual/driver/xf86-video-r128-6.13.0.tar.xz"
sha256 = "f20bed5ac201edd517fe0878dd2bcef78c8805c9f7faa3d0d7a4dba2e973f745"
source_dir = "xf86-video-r128-6.13.0"
deps = ["xorgproto"]
build_steps = ["./configure", "make", "make DESTDIR=${MAHOU_DESTDIR} install"]

[update]
check_url = "https://www.x.org/releases/individual/driver/"
version_pattern = "xf86-video-r128-([^\"/]+)\\.tar\\.xz"
source_template = "https://www.x.org/releases/individual/driver/xf86-video-r128-{version}.tar.xz"
source_dir_template = "xf86-video-r128-{version}"
