name = "xfce4-systemload-plugin"
version = "1.4.0"
description = "System load panel plugin for Xfce"
source = "https://archive.xfce.org/src/panel-plugins/xfce4-systemload-plugin/1.4/xfce4-systemload-plugin-1.4.0.tar.xz"
sha256 = "6e363bcf845bb88329b52858d65a1ec6e00db5121ae9246e46eb03135d9569c6"
source_dir = "xfce4-systemload-plugin-1.4.0"
deps = ["glib", "gtk+", "libxfce4ui", "xfce4-panel"]
build_steps = ["meson setup build --prefix=/usr --buildtype=release", "ninja -C build", "DESTDIR=${MAHOU_DESTDIR} ninja -C build install"]

[update]
check_url = "https://archive.xfce.org/src/panel-plugins/xfce4-systemload-plugin/1.4/"
version_pattern = "xfce4-systemload-plugin-([^\"/]+)\\.tar\\.xz"
source_template = "https://archive.xfce.org/src/panel-plugins/xfce4-systemload-plugin/1.4/xfce4-systemload-plugin-{version}.tar.xz"
source_dir_template = "xfce4-systemload-plugin-{version}"
