name = "xgamma"
version = "1.0.8"
description = "Alter monitor gamma correction through X11"
source = "https://www.x.org/releases/individual/app/xgamma-1.0.8.tar.xz"
sha256 = "98f9f69e53a11c354a6637ea5c3d7699ceb5c5b1f8ad6f0a14d9931e5a10d079"
source_dir = "xgamma-1.0.8"
deps = ["libX11", "xorg-proto"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://www.x.org/releases/individual/app/"
version_pattern = "xgamma-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://www.x.org/releases/individual/app/xgamma-{version}.tar.xz"
source_dir_template = "xgamma-{version}"
