name = "xkb-data"
version = "2.47"
description = "X keyboard configuration database"
source = "https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.47.tar.xz"
sha256 = "e59984416a72d58b46a52bfec1b1361aa7d84354628227ee2783626c7a6db6b6"
source_dir = "xkeyboard-config-2.47"
deps = ["xorg-proto"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]

[update]
check_url = "https://www.x.org/releases/individual/data/xkeyboard-config/"
version_pattern = "xkeyboard-config-([0-9]+\\.[0-9]+)\\.tar\\.xz"
source_template = "https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-{version}.tar.xz"
source_dir_template = "xkeyboard-config-{version}"
