name = "xsetpointer"
version = "1.0.1"
description = "Set X input device pointer mapping"
source = "https://www.x.org/releases/individual/app/xsetpointer-1.0.1.tar.gz"
sha256 = "54be93b20fd6f1deac67246d6e214a60b02dcfbf05295e43751f7a04edb986ac"
source_dir = "xsetpointer-1.0.1"
deps = ["libX11", "libXi", "xorg-proto"]

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://www.x.org/releases/individual/app/"
version_pattern = "xsetpointer-([0-9]+\\.[0-9]+\\.[0-9]+)\\.tar\\.gz"
source_template = "https://www.x.org/releases/individual/app/xsetpointer-{version}.tar.gz"
source_dir_template = "xsetpointer-{version}"
