name = "xz"
version = "5.8.3"
description = "Utils for managing LZMA compressed files"
source = "https://github.com/tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.gz"
sha256 = "3d3a1b973af218114f4f889bbaa2f4c037deaae0c8e815eec381c3d546b974a0"
source_dir = "xz-5.8.3"
deps = []

build_steps = [
  "./configure --prefix=/usr",
  "make",
  "make DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://github.com/tukaani-project/xz/releases"
version_pattern = "/releases/tag/v?([0-9][^\"/-]*)"
source_template = "https://github.com/tukaani-project/xz/releases/download/v{version}/xz-{version}.tar.gz"
source_dir_template = "xz-{version}"
