name = "yelp"
version = "49.1"
description = "GNOME help browser"
source = "https://download.gnome.org/sources/yelp/49/yelp-49.1.tar.xz"
sha256 = "3e3e94ef2d2c9487cc51062e3afbfa1578cebd29d80c84357b6d7ee6dcfd8a74"
source_dir = "yelp-49.1"
deps = ["glib", "gtk4", "yelp-xsl"]
build_steps = ["meson setup build --prefix=/usr --buildtype=release", "ninja -C build", "DESTDIR=${MAHOU_DESTDIR} ninja -C build install"]

[update]
check_url = "https://download.gnome.org/sources/yelp/49/"
version_pattern = "yelp-([^\"/]+)\\.tar\\.xz"
source_template = "https://download.gnome.org/sources/yelp/49/yelp-{version}.tar.xz"
source_dir_template = "yelp-{version}"
