name = "zstd"
version = "1.5.7"
description = "Fast real-time compression algorithm"
source = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz"
sha256 = "eb33e51f49a15e023950cd7825ca74a4a2b43db8354825ac24fc1b7ee09e6fa3"
source_dir = "zstd-1.5.7"
deps = []

build_steps = [
  "make PREFIX=/usr",
  "make PREFIX=/usr DESTDIR=${MAHOU_DESTDIR} install",
]

[update]
check_url = "https://github.com/facebook/zstd/releases"
version_pattern = "/releases/tag/([^\"/]+)"
source_template = "https://github.com/facebook/zstd/releases/download/v{version}/zstd-{version}.tar.gz"
source_dir_template = "zstd-{version}"
